modLoader="javafml"
loaderVersion="[47,)"
license="${mod_license}"

[[mods]]
modId="thirst_fix"
version="1.0"
displayName="Thirst Fix"
authors="hyygybs"
description='''${mod_description}'''

[[dependencies.thirst_fix]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.thirst_fix]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"